GENOME:
    "data/genome/biscutV2.1_new.fa"

# set SCAFFOLDS as "ALL" if you want to run on all scaffolds :: impliment only if limited number of scaffolds, else split snakemake into multiple jobs :: test it
# else give a txt file with names of scaffolds (one per line)
SCAFFOLDS:
    "ALL"

META:
    "test.tsv"

trim : True
tmpdir: "tmp"
suffix : ["_1","_2"]
platform : "A00574"

fastqc_threads: 10
trim_threads: 10
bwa_threads: 16
